spring:
  mvc:
    format:
      date: iso

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    properties:
      hibernate:
        hibernate:
          current_session_context_class: thread

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 999298694309-u1ri5ipilak3ud5nk2pn3gjkntdfvje1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google